AWSTemplateFormatVersion: 2010-09-09
Mappings:
  AWSRegionMap:
    us-west-2:
      Region: us-west-2a
    eu-central-1:
      Region: eu-central-1a
    ap-northeast-1:
      Region: ap-northeast-1a
      
Resources:  
  # VPCEUROPE config
  VPCEUROPE:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: VPCEUROPE
  
  IGWEUROPE:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: IGWEUROPE
  
  VPCEUROPEGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPCEUROPE
      InternetGatewayId: !Ref IGWEUROPE
  
  PublicSubnetEUROPE:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !FindInMap
      - AWSRegionMap
      - !Ref 'AWS::Region'
      - Region
      VpcId: !Ref VPCEUROPE
      CidrBlock: 10.0.100.0/24
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: "EUROPE-SUBNET"
  
  # Creating Routing tables for allowing traffic from one VPC to another
  # EUROPE 
  EUROPERouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCEUROPE
  
  EUROPEtoASIASubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetEUROPE
      RouteTableId: !Ref EUROPERouteTable

