AWSTemplateFormatVersion: 2010-09-09
Mappings:
  AWSRegionMap:
    us-west-2:
      Region: us-west-2a
    eu-central-1:
      Region: eu-central-1a
    ap-northeast-1:
      Region: ap-northeast-1a

Resources:
  # VPCUSA config
  VPCUSA:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.16.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: VPCUSA
  
  IGWUSA:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: "IGWUSA"

  VPCUSAGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPCUSA
      InternetGatewayId: !Ref IGWUSA

  PublicSubnetUSA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !FindInMap
        - AWSRegionMap
        - !Ref 'AWS::Region'
        - Region        
      VpcId: !Ref VPCUSA
      CidrBlock: 172.16.100.0/24
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: "USA-SUBNET"

  USARouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCUSA

  USAtoEUROPESubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetUSA
      RouteTableId: !Ref USARouteTable

